<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StudentInfo.aspx.cs" Inherits="StudentInformation.StudentInfo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css' media="screen" />
    <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
    <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
</head>
<body>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form id="form1" name="SignupForm" runat="server">
                <div class="contact-form" style="max-width: 500px; margin-left: 50px;">
                    <div class="container">
                        <h1 class="form-horizontal">Information </h1>

                        <div class="form-group row">
                            <asp:Label class="col-sm-2 col-form-label" runat="server" Text="Roll No" Font-Bold="true" />
                            <div class="col-md-1">
                                <asp:Label runat="server" ID="lblRollNo" Font-Bold="true" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <asp:Label class="col-sm-2 col-form-label" runat="server" Text="First Name" Font-Bold="true" />
                            <div class="col-md-3">
                                <asp:TextBox runat="server" CssClass="form-control" ID="txtStudentFirstName" name="Nametxt" placeholder="Enter Student`s First Name" />
                                <asp:RequiredFieldValidator ID="StudentFirstNameValidator" runat="server" ControlToValidate="txtStudentFirstName" ErrorMessage="* Student First Name Required" ForeColor="#FF3300" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <asp:Label class="col-sm-2 col-form-label" runat="server" Text="Last Name" Font-Bold="true" />
                            <div class="col-md-3">
                                <asp:TextBox runat="server" CssClass="form-control" ID="txtStudentLastName" name="Nametxt" placeholder="Enter Student`s Last Name" />
                                <asp:RequiredFieldValidator ID="StudentLastNameValidator" runat="server" ControlToValidate="txtStudentLastName" ErrorMessage="* Student Last Name Required" ForeColor="#FF3300" />
                            </div>
                        </div>
                        <div class="form-group row">

                            <asp:Label class="col-sm-2 col-form-label" runat="server" Text="Gender" Font-Bold="true" />
                            <div class="col-md-3">
                                <asp:RadioButtonList runat="server" ID="rdolstgender" RepeatDirection="Horizontal" RepeatLout="Flow" >
                                    <asp:ListItem Text="Male" Value="Male"></asp:ListItem>
                                    <asp:ListItem Text="Female" Value="Female"></asp:ListItem>
                                </asp:RadioButtonList>
                                <asp:RequiredFieldValidator ID="GenderValidator" runat="server" ControlToValidate="rdolstgender" ErrorMessage="* Gender Required" ForeColor="#FF3300"></asp:RequiredFieldValidator>
                            </div>
                        </div>

                        <div class="form-group row">
                            <asp:Label class="col-sm-2 col-form-label" runat="server" Text="Cources" Font-Bold="true" />
                            <div class="col-md-3">
                                <asp:CheckBoxList ID="cblSubjects" runat="server"  ></asp:CheckBoxList>                          
                            </div>
                        </div>

                        <div class="form-group row">
                            <asp:Button Class="btn btn-primary" ID="btnSubmit" runat="server" Text="Submit" OnClick="onSubmit" Style="width: 69px" />
                        </div>

                    </div>
                </div>

                <div>
                    <asp:GridView ID="gvStudentRecord" BackColor="WhiteSmoke" ShowFooter="True"  AutoGenerateDeleteButton="true" DataKeyNames="StudID" AutoGenerateColumns="false" OnRowEditing="GridViewRowEdit" OnRowUpdating="GridViewRowUpdating"  OnRowCancelingEdit="GridViewRowCancelingEdit" OnRowDeleting="GridViewRowDelete" AutoGenerateEditButton="true"  runat="server"  BorderColor="CornflowerBlue" CellPadding="15">
                        <Columns>
                           
                           <asp:TemplateField  HeaderText="Roll No" ItemStyle-HorizontalAlign="Center"   ControlStyle-Font-Bold="true" ItemStyle-VerticalAlign="Middle"  >
                                <ItemTemplate >
                                    <asp:Label ID="RollNo" runat="server" ReadOnly="true"  Text='<%#Bind("StudID") %>' />                                                    
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="First Name" ItemStyle-HorizontalAlign="Center"   ControlStyle-Font-Bold="true" ItemStyle-VerticalAlign="Middle"  >
                                <ItemTemplate >
                                    <asp:TextBox ID="FirstName" runat="server"   Text='<%#Bind("FirstName") %>' /> 
                                    <asp:RequiredFieldValidator ID="FirstNameValidator" runat="server" ControlToValidate="FirstName" ErrorMessage="* First Name Required" ForeColor="#FF3300"/>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Last Name" ItemStyle-HorizontalAlign="Center"   ControlStyle-Font-Bold="true" ItemStyle-VerticalAlign="Middle"  >
                                <ItemTemplate >
                                    <asp:TextBox ID="LastName" runat="server"   Text='<%#Bind("LastName") %>' /> 
                                    <asp:RequiredFieldValidator ID="LastNameValidator" runat="server" ControlToValidate="LastName" ErrorMessage="* Last Name Required" ForeColor="#FF3300"/>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Gender" ItemStyle-HorizontalAlign="Center"   ControlStyle-Font-Bold="true" ItemStyle-VerticalAlign="Middle"  >
                                <ItemTemplate >
                                    <asp:Label ID="Gender" ReadOnly="true" runat="server" Text='<%#Bind("Gender") %>' />                                                    
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Subject Name" ItemStyle-HorizontalAlign="Center"   ControlStyle-Font-Bold="true" ItemStyle-VerticalAlign="Middle"  >
                                <ItemTemplate >
                                    <asp:TextBox ID="SubName" runat="server" ReadOnly="true"  Text='<%#Bind("SubName") %>' />                                                    
                                </ItemTemplate>
                            </asp:TemplateField>
  
                        </Columns>
                        <FooterStyle BackColor="Silver" Height="10px" />
                        <PagerStyle BackColor="DarkGray" />
                        <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                    </asp:GridView>

                    
                </div>
            </form>
        </div>
    </div>

    <div>
        <div>
        </div>
    </div>

</body>
</html>
